[workspace]
members = [
    "anndata",
    "anndata-hdf5",
    "pyanndata",
    "anndata-test-utils",
    "python",
]
resolver = "2"

[workspace.dependencies]
anndata = { path = "anndata" }
anndata-hdf5 = { path = "anndata-hdf5" }
pyanndata = { path = "pyanndata" }